"""add org_id column to project table

Revision ID: 48f5f83224b4
Revises: 
Create Date: 2026-03-07 03:16:18.895599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f5f83224b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'organization', 'users', ['owner_id'], ['id'])
    op.add_column('projects', sa.Column('org_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'organization', ['org_id'], ['id'])
    op.create_foreign_key(None, 'task', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'org_id')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    # ### end Alembic commands ###
