"""add age to user

Revision ID: e5c8537ca790
Revises: b766a9dc519c
Create Date: 2026-02-19 12:09:41.790544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c8537ca790'
down_revision: Union[str, Sequence[str], None] = 'b766a9dc519c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False, server_default='20'))
    # optional: remove server_default after populating data
    op.alter_column('users', 'age', server_default=None) # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
